<div class="page-limit-width">
    <div class="page-heading">
        <div class="page-heading-breadcrumbs"><a href="/legal/terms-of-service">Terms of Service</a></div>					</div>
    <div class="page-description">
        <div class="page-description-display-state">
            <div class="markdown markdown--resize-body"><p>The following terms and conditions govern all use of the ChallengeWars website (further known as, the "Website"), and all content, services and products available at or through the Website. The entity controlling the Website is defined as "ChallengeWars", "we", "us" or "our". The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies.</p>
                <p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the Website, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by ChallengeWars, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>
                <ol><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ullamcorper, nisl ut mattis consequat, nibh nisl scelerisque libero, nec viverra ligula turpis in nulla. Suspendisse iaculis sem convallis, laoreet justo quis, viverra purus. Cras tristique, orci sit amet maximus accumsan, nisi dolor commodo nulla, in mattis arcu sem in sem. Morbi viverra turpis magna, in commodo urna feugiat quis. Vestibulum ex felis, bibendum id lorem et, consectetur lacinia dolor. Pellentesque sed nisi vitae nulla vulputate tristique eget in nisi. Integer sit amet pellentesque nunc. Proin a mollis lorem. Etiam dictum sed magna vitae aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</li>

                    <li>Nunc in ante eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut non odio et est scelerisque laoreet eget in neque. In eleifend, diam eu porta dignissim, augue mi laoreet eros, in facilisis nibh metus eu neque. Pellentesque id velit vitae enim vehicula ullamcorper. Integer pretium malesuada nibh, faucibus tristique risus rutrum id. Pellentesque egestas quam at ante efficitur, in sodales nibh efficitur.</li>

                    <li>Suspendisse quis enim aliquet tortor efficitur fringilla. Suspendisse convallis augue in posuere lobortis. Vivamus at diam semper, sagittis purus quis, molestie odio. Vestibulum semper nulla ut urna volutpat tempus. Nam fringilla euismod luctus. Fusce id lobortis enim, non porttitor purus. Integer ultrices mauris et nisi faucibus scelerisque. Phasellus quis lacus vel ante luctus ultrices. Integer velit odio, varius sit amet velit sit amet, dignissim auctor orci. Maecenas a ullamcorper sapien. Sed sodales sodales magna et laoreet. Praesent dapibus neque id pharetra ullamcorper. Mauris vitae lacinia ante. In ut mi non neque varius accumsan. Mauris tempus nulla magna, et laoreet neque egestas nec.</li>

                    <li>Proin malesuada leo erat, eget cursus erat gravida quis. Fusce hendrerit condimentum posuere. Praesent non lacus ipsum. Nunc a nisl tristique, bibendum ligula sit amet, tempus sem. Proin vel tincidunt magna. Praesent auctor orci porta felis facilisis blandit. Sed arcu urna, bibendum eget quam sed, varius gravida arcu. Praesent porta ac nisl eget viverra. In fringilla cursus neque vel pellentesque. Mauris turpis nisi, dignissim eget maximus eu, ornare vel ipsum.</li>

                    <li>Mauris nunc enim, commodo sit amet tempus in, efficitur viverra leo. Suspendisse enim odio, aliquet eu justo sit amet, euismod tristique mi. Ut elementum nulla eu sapien molestie, vel semper justo suscipit. Aenean semper ultrices eros, a laoreet nulla maximus sit amet. Proin mauris neque, mollis ac dapibus nec, elementum vel nisi. Integer et est euismod, luctus orci vel, fermentum massa. Aenean id iaculis lectus. In ut varius ligula. Quisque tempus, lorem vel feugiat ornare, lacus purus iaculis magna, quis mattis mi justo tincidunt felis. Suspendisse a viverra neque, vel dapibus risus. Proin metus lectus, finibus maximus sem sit amet, dapibus pharetra massa. Morbi venenatis nunc sed ante mollis, convallis tempor dolor suscipit. Pellentesque ultricies nisi ut imperdiet bibendum. Cras luctus, augue ut tristique luctus, est dui volutpat nisi, fringilla faucibus neque diam non tellus.</li>

                    <li>Nunc lobortis pulvinar tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec dapibus egestas varius. Praesent sed est interdum nisi eleifend pretium. Aenean porttitor maximus condimentum. Cras eleifend, mi quis malesuada vestibulum, diam nisl tempor neque, non dapibus leo sem sit amet tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas faucibus augue elit, id maximus est iaculis non. Suspendisse quis nunc metus. Maecenas quis metus quis augue dapibus accumsan. Ut sem nibh, porta quis accumsan sed, eleifend sit amet nibh. Ut tempor dignissim odio non scelerisque.</li>

                    <li>Proin ultrices, magna ut ultricies condimentum, felis metus malesuada dui, quis fermentum mi mauris vitae nisi. Nullam sed leo sit amet enim pharetra elementum vel viverra dui. Aliquam tincidunt gravida porta. Duis placerat iaculis ex, et lacinia turpis aliquam non. Suspendisse vehicula mollis lacus nec egestas. Mauris ac hendrerit metus, sed vestibulum massa. Donec ut urna posuere, volutpat erat eget, hendrerit lectus.</li>

                    <li>Nullam sem dolor, tincidunt non aliquam ut, suscipit tempor arcu. Morbi auctor fermentum ante, ac eleifend magna faucibus sit amet. Integer eget massa posuere, bibendum ipsum a, accumsan ligula. Ut elit magna, mollis malesuada mauris et, bibendum tempor metus. Cras consequat sed orci sed elementum. Donec dictum tortor vitae tortor malesuada, vel lobortis urna auctor. Nam pretium euismod iaculis. Nam aliquam congue tincidunt. Suspendisse et ligula vel magna sollicitudin vehicula. Quisque eleifend tellus ante, sed mattis ligula vehicula a. Praesent ornare lacus sit amet nisl scelerisque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ut dolor pretium, dapibus ligula nec, sollicitudin sapien.</li>

                    <li>Maecenas placerat, arcu non suscipit feugiat, orci justo porttitor leo, sed vehicula est justo ac nisi. Suspendisse ac iaculis sem, non pellentesque diam. Praesent feugiat elementum consectetur. Morbi urna enim, tincidunt ac commodo et, vulputate quis enim. Morbi tempor sed lorem ut fermentum. Integer at facilisis tellus. Proin convallis, metus eget interdum laoreet, magna lectus dapibus nisi, eget rutrum turpis lacus et nunc. Etiam hendrerit non nisl nec tempus. Donec aliquet diam magna, in condimentum massa dictum placerat. Donec id libero vitae quam convallis porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas quis libero in eros pellentesque convallis eget malesuada felis. Donec vehicula sed justo at accumsan. Nunc tincidunt erat lacus, et tincidunt orci pharetra vel.</li>

                    <li>Morbi et tempus ipsum. Morbi eu iaculis enim, ac tempor nunc. Proin sapien elit, scelerisque et massa sit amet, feugiat dignissim lorem. Curabitur quis dui quis dui pulvinar gravida. Integer pretium sem sapien, quis sodales mauris lobortis ut. Phasellus eros metus, vulputate quis lacinia fermentum, pretium at mi. Praesent sagittis imperdiet sem, a iaculis urna sagittis ut. Nullam ultricies, enim eget convallis rhoncus, sem urna posuere ex, eget venenatis augue mauris at tellus. Praesent in eros mi. Aliquam pharetra posuere augue ac dapibus. Mauris venenatis sit amet tortor tempor elementum. Sed imperdiet ornare lacus eget ullamcorper. Integer laoreet eros non enim tempus aliquet. Curabitur tempus condimentum urna, posuere eleifend quam laoreet a.</li>

                    <li>Ut sollicitudin blandit rutrum. Mauris hendrerit dui vel ligula ornare, vitae iaculis nisi dapibus. Etiam aliquam lobortis varius. Mauris posuere tempus egestas. Duis volutpat tempor sagittis. Sed dictum mi at massa pretium aliquet. Maecenas finibus sapien nisl, ut varius libero pretium quis.</li>

                    <li>Nunc aliquam lorem at elementum consectetur. Nullam eget lacus volutpat, aliquam lectus sit amet, efficitur nulla. Aliquam mauris lacus, euismod id ante non, dapibus vulputate orci. Integer imperdiet rutrum libero, quis pulvinar ante malesuada at. Mauris eget malesuada enim. Vivamus et mi nisi. Ut quis lorem fermentum, malesuada ipsum ac, lobortis est. Vivamus sollicitudin nulla nec ex faucibus, sit amet pretium ligula egestas. Nam eu consectetur justo. Mauris lacus ante, laoreet at dui eget, facilisis mattis nibh.</li>

                    <li>Proin velit nunc, vestibulum eget ex sit amet, tempus vulputate mi. Donec feugiat sem sit amet finibus hendrerit. Aliquam eleifend aliquet tortor vulputate consectetur. Maecenas vel posuere nibh. Pellentesque vel auctor nisi. Quisque vel ante venenatis, varius massa ac, vulputate elit. Proin molestie erat eu neque tristique luctus.</li>

                    <li>Aenean dolor orci, feugiat ac magna iaculis, vulputate egestas erat. Nunc et vestibulum augue. Praesent id lacinia felis. Phasellus ut feugiat ante, id placerat nisi. Donec quis tortor neque. Pellentesque iaculis nulla id felis maximus scelerisque. Nulla convallis dignissim vestibulum. Phasellus porttitor felis ligula, id euismod mi eleifend vitae. Integer facilisis viverra blandit. Donec non diam libero. Proin scelerisque, turpis et accumsan maximus, ipsum leo egestas dui, ac ultricies arcu purus vel lorem. Nulla imperdiet nulla augue, ut rutrum libero ullamcorper ut. Suspendisse est arcu, fermentum iaculis fringilla ac, accumsan ut lorem. Aliquam vitae finibus urna. In hac habitasse platea dictumst. Curabitur egestas arcu vitae ante laoreet, sit amet aliquam lorem euismod.</li>
                </ol></div>

            <div class="notification notification--warning notification--margin-top">
                <i class="fa fa-edit"></i> Last modified <span title="February 28, 2015, 03:33">28 February</span> by <a href="/user/ChypRiotE">ChypRiotE</a>.</div>
        </div>
    </div>
</div>